// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calculate(arg1) {
  return window['go']['root']['App']['Calculate'](arg1);
}

export function CreateNewField(arg1, arg2) {
  return window['go']['root']['App']['CreateNewField'](arg1, arg2);
}

export function CreateTable(arg1) {
  return window['go']['root']['App']['CreateTable'](arg1);
}

export function CreateTableData(arg1) {
  return window['go']['root']['App']['CreateTableData'](arg1);
}

export function DeleteField(arg1, arg2, arg3) {
  return window['go']['root']['App']['DeleteField'](arg1, arg2, arg3);
}

export function DeleteTable(arg1, arg2) {
  return window['go']['root']['App']['DeleteTable'](arg1, arg2);
}

export function DeleteTableData(arg1, arg2) {
  return window['go']['root']['App']['DeleteTableData'](arg1, arg2);
}

export function GetAllTableData(arg1) {
  return window['go']['root']['App']['GetAllTableData'](arg1);
}

export function GetAllTables() {
  return window['go']['root']['App']['GetAllTables']();
}

export function UpdateTableData(arg1) {
  return window['go']['root']['App']['UpdateTableData'](arg1);
}
