port: '5000'

postgres:
    name: price
    host: 127.0.0.1
    port: 5432
    ssl: disable
    username: postgres
redis:
    db: 0
    host: 192.168.5.159
    port: 6379

auth:
    accesstokenttl: 20m
    countattempt: 5
    limitauthttl: 30m
    refreshtokenttl: 24h
    secure: false

cache:
    ttl: 3600s
http:
    host: http://localhost
    maxheaderbytes: 1
    port: 8080
    readtimeout: 10s
    servicename: api-service
    writetimeout: 10s
limiter:
    burst: 20
    rps: 10
    ttl: 10m
